### ISSUE TITLE
I am getting error InvalidPulseCount: Expected 84 but got 0 pulses

### ISSUE THREAD

**Issue by ragasjohn** [ikornaselur/pico-libs#1]
Hello when I try to run your code I get this error

Traceback (most recent call last):
  File "<stdin>", line 37, in <module>
  File "dht.py", line 58, in temperature
  File "dht.py", line 43, in measure
InvalidPulseCount: Expected 84 but got 0 pulses

Any ideas? 

Thanks

**Comment by ikornaselur** [comment]
Hey there!

It would seem that the Pico isn't getting any responses back from the sensor.

If this is still an issue, can you post your whole code that is using this and ideally show the wiring you have with your Raspberry Pi Pico?

**Comment by ragasjohn** [comment]
Hey,

thanks for the response. Yes the problem is with the sensor. I ve changed it and works now.
